# Generated by Django 4.2.6 on 2023-10-14 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('joinbackendapp', '0004_rename_subtasks_task_subtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
