# Generated by Django 4.2.6 on 2023-10-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joinbackendapp', '0007_alter_subtask_task_remove_task_assigned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='joinbackendapp.contact'),
        ),
    ]
