# Generated by Django 4.2.6 on 2023-10-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joinbackendapp', '0008_alter_task_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='initials',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
