# Generated by Django 4.2.6 on 2023-11-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joinbackendapp', '0011_rename_due_date_task_duedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('urgent', 'Urgent')], default='low', max_length=10),
        ),
        migrations.DeleteModel(
            name='Priority',
        ),
    ]
