# Generated by Django 4.2.6 on 2023-11-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joinbackendapp', '0012_alter_task_priority_delete_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('Urgent', 'Urgent')], default='low', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('To do', 'Todo'), ('In Progress', 'Inprogress'), ('Awaiting Feedback', 'Awaitingfeedback'), ('Done', 'Done')], default='To do', max_length=30),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
